application:
  port: 8083


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/email
    username: postgres
    password: Roberto2101#
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: amqps://xjjvakqt:67tjRR6LVJc0d6uvIAWwAqjS347Fkrel@jackal.rmq.cloudamqp.com/xjjvakqt
    queue: ms-email




